package lt.vu.PSK1lab.mybatis.dao;

import java.util.List;
import lt.vu.PSK1lab.mybatis.model.Band;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    int insert(Band record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    Band selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    List<Band> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    int updateByPrimaryKey(Band record);
}