package lt.vu.PSK1lab.mybatis.dao;

import java.util.List;
import lt.vu.PSK1lab.mybatis.model.Festival;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FestivalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FESTIVAL
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FESTIVAL
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    int insert(Festival record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FESTIVAL
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    Festival selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FESTIVAL
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    List<Festival> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FESTIVAL
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    int updateByPrimaryKey(Festival record);
}