package lt.vu.PSK1lab.mybatis.model;

public class Festival {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FESTIVAL.ID
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FESTIVAL.NAME
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FESTIVAL.ID
     *
     * @return the value of PUBLIC.FESTIVAL.ID
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FESTIVAL.ID
     *
     * @param id the value for PUBLIC.FESTIVAL.ID
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FESTIVAL.NAME
     *
     * @return the value of PUBLIC.FESTIVAL.NAME
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FESTIVAL.NAME
     *
     * @param name the value for PUBLIC.FESTIVAL.NAME
     *
     * @mbg.generated Mon Apr 05 00:33:25 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}